# numpy形态

## 改变维度长度或者秩(rank)

In [3]:
import numpy as np
a = np.floor(10*np.random.random((3,4)))
print(a)

[[8. 4. 8. 7.]
 [2. 4. 8. 5.]
 [6. 7. 6. 8.]]


使用ravel()函数，获取所有元素组成一维array，注意，**返回的一维array仍然是共享数据的**，做个试验：

In [7]:
a = np.floor(10*np.random.random((3,4)))
print(a)
b = a.ravel()
b[0] = -1
print(a)

[[5. 5. 2. 3.]
 [9. 1. 8. 4.]
 [7. 2. 3. 0.]]
[[-1.  5.  2.  3.]
 [ 9.  1.  8.  4.]
 [ 7.  2.  3.  0.]]


可以看到，改变了b的元素，a的元素也跟着改变，这是一定要注意的；
改变一个多维数组的各个维度长度，直接赋值给shape属性，如果获取另一个array，ravel()/reshape()/transpose()都可以，同样的，**元素数据仍然是共享的，shadecopy**

In [13]:
a = np.floor(10*np.random.random((3,4)))
print(a.shape)
print(a.reshape((2,6)))#reshape()不会直接改变a
print(a)
a.shape = (4,3)#这里直接改变了a
print(a)
print(a.transpose())#转置也没有直接改变a
print(a)

(3, 4)
[[3. 2. 3. 0. 9. 5.]
 [6. 9. 0. 5. 3. 0.]]
[[3. 2. 3. 0.]
 [9. 5. 6. 9.]
 [0. 5. 3. 0.]]
[[3. 2. 3.]
 [0. 9. 5.]
 [6. 9. 0.]
 [5. 3. 0.]]
[[3. 0. 6. 5.]
 [2. 9. 9. 3.]
 [3. 5. 0. 0.]]
[[3. 2. 3.]
 [0. 9. 5.]
 [6. 9. 0.]
 [5. 3. 0.]]


额外一个小tip：如果使用-1指定shape，意味着自动计算这个axis长度：

In [14]:
a = np.random.randint(0,10,(3,4))
print(a)

[[5 5 6 4]
 [2 8 3 1]
 [0 0 1 6]]


In [15]:
a.shape = (-1,6)
print(a)

[[5 5 6 4 2 8]
 [3 1 0 0 1 6]]


## array组合、拼接

In [16]:
a = 10*np.random.random((2,2))
b = 10*np.random.random((2,2))
print(a)
print('-'*8)
print(b)

[[0.26104778 9.52801532]
 [8.17661164 1.32773419]]
--------
[[2.93207727 5.95129093]
 [4.46894076 1.99406665]]


In [18]:
c = np.hstack((a,b))
print(c)
a[0,0]=-1
print(c)

[[0.26104778 9.52801532 2.93207727 5.95129093]
 [8.17661164 1.32773419 4.46894076 1.99406665]]
[[0.26104778 9.52801532 2.93207727 5.95129093]
 [8.17661164 1.32773419 4.46894076 1.99406665]]


可以看到，拼接是深拷贝

In [19]:
d = np.vstack((a,b))
print(d)

[[-1.          9.52801532]
 [ 8.17661164  1.32773419]
 [ 2.93207727  5.95129093]
 [ 4.46894076  1.99406665]]


In [20]:
c = np.column_stack((a,b))
print(c)

[[-1.          9.52801532  2.93207727  5.95129093]
 [ 8.17661164  1.32773419  4.46894076  1.99406665]]


In [24]:
a = np.array([[1,2],[3,4]])
b = np.array([8,8])
# b = np.array([[8],[8]])  这两种出来的结果是一样的，也就是说column_stack是强制添加到列的
print(np.column_stack((a,b)))

[[1 2 8]
 [3 4 8]]


一个彩蛋：

In [26]:
a = np.array([4,2])
b = np.array([2,8])
print(a[:,np.newaxis])
print(np.column_stack((a,b)))

[[4]
 [2]]
[[4 2]
 [2 8]]


## array拆分

In [27]:
a = np.floor(10*np.random.random((2,6)))
print(a)

[[9. 7. 4. 6. 2. 0.]
 [6. 4. 2. 9. 6. 4.]]


In [28]:
b = np.hsplit(a,3)
print(b)

[array([[9., 7.],
       [6., 4.]]), array([[4., 6.],
       [2., 9.]]), array([[2., 0.],
       [6., 4.]])]


In [29]:
b[0][0,0] = -9
print(a)

[[-9.  7.  4.  6.  2.  0.]
 [ 6.  4.  2.  9.  6.  4.]]


**说明拆分返回的array列表仍然共享原来的数据**

In [30]:
b = np.hsplit(a,(3,4))#从第三列和第四列后拆分
print(b)

[array([[-9.,  7.,  4.],
       [ 6.,  4.,  2.]]), array([[6.],
       [9.]]), array([[2., 0.],
       [6., 4.]])]
