# numpy高级主题
## 通用函数

In [1]:
import numpy as np
a = np.arange(0, 9, dtype=np.int32).reshape((3,3))
print(a)
print(a+10)
print(a-2)
print(a*3)
print(a/4)
print(a//4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]
[[0.   0.25 0.5 ]
 [0.75 1.   1.25]
 [1.5  1.75 2.  ]]
[[0 0 0]
 [0 1 1]
 [1 1 2]]


`+ - * / //`这些运算符在numpy当中类似c++的操作符重载，numpy会把这些操作符用内置的通用函数替换；

In [2]:
print(a+10)
print(np.add(a, 10))

[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [3]:
print(a*3)
print(np.multiply(a, 3))

[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]
[[ 0  3  6]
 [ 9 12 15]
 [18 21 24]]


In [4]:
print(a/4)
print(np.divide(a, 4))

[[0.   0.25 0.5 ]
 [0.75 1.   1.25]
 [1.5  1.75 2.  ]]
[[0.   0.25 0.5 ]
 [0.75 1.   1.25]
 [1.5  1.75 2.  ]]


其他的通用函数包括np.abs, np.power, np.sin, np.cos, np.arcsin, np.exp, np.exp2, np.log, np.log2, np.log10

## 通用函数聚合

In [6]:
a = np.arange(1, 6)
np.add.reduce(a)

15

In [7]:
np.multiply.reduce(a)

120

In [8]:
np.multiply.accumulate(a)

array([  1,   2,   6,  24, 120], dtype=int32)

## 求和与最大最小值

In [10]:
a = np.random.randint(1, 15, size=(4, 4))
print(a)
np.sum(a)

[[ 4  3  3 11]
 [12  6  6  9]
 [10 12  4  9]
 [10  6  5  3]]


113

In [11]:
np.sum(a, axis=0)

array([36, 27, 18, 32])

In [12]:
np.min(a)

3

In [13]:
np.argmin()

1

|函数名|描述|
|:---:|:---:|
|np.sum|计算元素的和|
|np.prod|计算元素的积|
|np.mean|平均值|
|np.std|标准差|
|np.var|方差|
|np.min|最小值|
|np.max|最大值|
|np.argmin|最小值索引|
|np.argmax|最大值索引|
|np.median|中位数|
|np.any|任何一个元素满足条件|
|np.all|所有元素满足条件|