# numpy 笔记
## 创建ndarray

In [1]:
import numpy as np
np.zeros(10, dtype=np.int32)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [2]:
np.zeros((3, 3), dtype=np.int32)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [3]:
np.ones((2,3), dtype=np.int)

array([[1, 1, 1],
       [1, 1, 1]])

In [4]:
np.full((2, 2), 2.3748)

array([[2.3748, 2.3748],
       [2.3748, 2.3748]])

In [5]:
np.arange(0, 10, 1) # 从0开始到10（不包括10）， step=1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [7]:
# 创建在0~1范围内均匀分布的4x4数组
np.random.random((4, 4))

array([[0.72503449, 0.62269738, 0.18420923, 0.70127595],
       [0.10077625, 0.68021506, 0.38950636, 0.72826839],
       [0.91946449, 0.57214639, 0.63580521, 0.86445747],
       [0.7256251 , 0.5041474 , 0.16634695, 0.87169821]])

In [8]:
# 创建均值为0， 方差为1的正态分布的4x4数组
np.random.normal(0, 1, (4,4))

array([[-2.05079301e-03, -2.39827039e-01, -7.56344067e-01,
        -1.74451327e-01],
       [ 2.86549519e+00, -6.85071456e-01,  1.43949278e-01,
        -3.42048170e-02],
       [-1.92143145e+00,  7.44440506e-01,  1.14612373e+00,
        -1.38075771e+00],
       [ 1.43175350e-01,  4.28539898e-01, -5.70884127e-01,
         1.55962624e+00]])

In [15]:
# 创建3x3 0~10之间的随机整数数组
print(np.random.randint(0, 10, (3,3)))
# randint(low, high=None, size, dtype) 如果没有给出high， 则结果为randint(0, low)
print(np.random.randint(3, size=(3,3)))

[[9 7 3]
 [7 0 4]
 [9 7 9]]
[[0 0 0]
 [2 1 2]
 [2 2 1]]


In [10]:
# 创建单位矩阵
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
# 创建未初始化的数组
np.empty((3,3))

array([[9.42700522e-312, 9.42700522e-312, 9.42700522e-312],
       [9.42700522e-312, 9.42700522e-312, 9.42700522e-312],
       [9.42700522e-312, 9.42700522e-312, 3.60739285e-313]])

In [20]:
mat = np.random.random(size=(2,2))
print(mat.ndim)
print(mat.shape)
print(mat.dtype)
print(mat.itemsize)
print(mat.nbytes)

2
(2, 2)
float64
8
32


ndarray的基础属性ndim = 数组维数, shape=数组维度, dtype=元素类型, itemsize=元素大小, nbytes=所有元素总共占用的空间

## 访问元素

In [22]:
from collections import Iterable, Iterator
mat = np.random.random(size=(3,3))
print(mat)
isinstance(mat, Iterable)

[[0.57884058 0.65263147 0.16057166]
 [0.92903005 0.93447527 0.39819271]
 [0.21159292 0.91391116 0.10429927]]


True

np.ndarray也是可迭代对象

In [23]:
mat[0, 0]

0.5788405824309808

In [24]:
mat[0]

array([0.57884058, 0.65263147, 0.16057166])

In [25]:
mat[0, :]

array([0.57884058, 0.65263147, 0.16057166])

In [26]:
mat[0, -1]

0.16057166106206744

类似list切片
## 修改元素

In [27]:
print(mat)

[[0.57884058 0.65263147 0.16057166]
 [0.92903005 0.93447527 0.39819271]
 [0.21159292 0.91391116 0.10429927]]


In [28]:
mat[0, 0] = 0.0
print(mat)

[[0.         0.65263147 0.16057166]
 [0.92903005 0.93447527 0.39819271]
 [0.21159292 0.91391116 0.10429927]]


## 访问子数组

In [29]:
mat = np.arange(0, 10, 1)
print(mat)

[0 1 2 3 4 5 6 7 8 9]


In [30]:
mat[0:4]

array([0, 1, 2, 3])

In [31]:
mat[:4]

array([0, 1, 2, 3])

In [32]:
mat[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [33]:
mat[::2]

array([0, 2, 4, 6, 8])

In [34]:
mat[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [35]:
mat[6::-1]

array([6, 5, 4, 3, 2, 1, 0])

In [36]:
mat[9::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [40]:
mat.flags.owndata

True

In [42]:
mat_b = mat[0:2]
mat_b.flags.owndata

False

注意，通过索引得到的子数组不拥有data，公用母数组的data，如果修改子数组，母数组也会跟着改变；
可以通过copy()方法得到副本

In [43]:
mat_b = mat[0:2].copy()
mat_b.flags.owndata

True

## ndarray拼接与分裂
拼接主要有concatenate, hstack, vstack, dstack 方法

In [45]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate([a, b]))

[1 2 3 4 5 6]


In [46]:
print(np.concatenate([a, b, a]))

[1 2 3 4 5 6 1 2 3]


应用在二维数组

In [47]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
np.concatenate([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [48]:
np.concatenate([a, a], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [50]:
np.vstack([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [51]:
c = np.array([[99], [99]])
np.hstack([a, c])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

dstack同理，在第三个维度上拼接

分裂对应的是split, hsplit, vsplit方法

In [52]:
x = np.arange(0, 10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [53]:
np.split(x, [3, 7])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [54]:
a = np.arange(0, 16).reshape((4, 4))
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [56]:
a1, a2 = np.vsplit(a, [2])
print(a1)
print(a2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [57]:
a1, a2 = np.hsplit(a, [2])
print(a1)
print(a2)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
